[versions]
# Plugins
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
kover = "0.9.1"
dokka = "2.0.0"
kotlinter = "5.1.1"
pluginYml = "0.7.1"
minecraftServer = "3.2.1"
shadow = "8.1.1"
kotlinpoet = "2.2.0"

# Libraries
spigot8 = "1.8.8-R0.1-SNAPSHOT"
spigot = "1.21.7-R0.1-SNAPSHOT"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
pluginYml-bukkit = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "pluginYml" }
minecraftServer = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraftServer" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
spigot8 = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot8" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
